### ISSUE TITLE
Don’t use develop branch anymore

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#194]
Another heads up.  @ffd8 @trych 

I will drop the featurebranch -> develop -> master method for this repo. Since I am mostly the only one developing in it and we don’t do Release Cycles in the page it only creates overhead. 

So from now on it should be featurebranch -> passing tests? -> Master

**Comment by ffd8** [comment]
@fabianmoronzirfas Sounds good and thanks for all the organizational backend to this!

Curious if you know how to quiet/reduce the email notifiactions specific to things the `renovate` & `basilbot` are doing? Checked out settings -> notifications, but didn't find any preferences (maybe on bot setup themselves?) – Would appreciate to only get emails about human chatter on issues, since the bot stuff is usually visible on the PR progress page themselves.

**Comment by fabianmoronzirfas** [comment]
I don't think the bot can control the notifications for PRs. 

https://docs.renovatebot.com/configuration-options/#suppressnotifications

**Comment by fabianmoronzirfas** [comment]
BTW. As soon as all the initial PRs are done it will be a little more quieter around renovate bot :)
