### ISSUE TITLE
Use markdownify for descriptions

### ISSUE THREAD

**Issue by fabianmoronzirfas** [basiljs/basiljs.github.io#20]

**Comment by fabianmoronzirfas** [comment]
@trych ping

**Comment by trych** [comment]
Ok, so I tested this some more, it works quite well. We could use it for inline code, links and lists (and italic and bold, I guess).

I would suggest we add the `markdownify` keyword to `{{include.entry.description}}`, to `{{param.description}}` and to `{{include.entry.returns.description}}`. @fabianmoronzirfas, do you want me to prepare a branch with these changes?

The only thing that remains is fixing the CSS for these inline code snippets. I don't know the SASS syntax, so maybe someone could jump in and do this for me.

**Comment by fabianmoronzirfas** [comment]
Are you talking about doing changes in here? --> https://github.com/basiljs/basiljs.github.io/blob/master/_includes/entry-card.html

**Comment by fabianmoronzirfas** [comment]
The Basic SCSS for styling the Code snippets should be in place already --> see e.g. https://basiljs.github.io/document/stories.html (comes from here https://github.com/basiljs/basiljs.github.io/blob/master/_sass/_syntax.scss) We will just need to check if it does style inline code as well

**Comment by trych** [comment]
Yes, the formatting for lists and links works fine already, the formatting for inline code not yet.
The problem seems to be that when this markdownify process is used, the descriptions don't end in the `<p class="descriptions">` tag, but creates a new p tag after it. That's why it is not targeted by the `.descriptions code {}` CSS anymore.

After markdownify, the rendering looks like this:

![bildschirmfoto 2018-04-11 um 11 16 25](https://user-images.githubusercontent.com/9803905/38608952-1e20cec6-3d7d-11e8-9a68-be62ce6c1e0f.png)
---
![bildschirmfoto 2018-04-11 um 11 17 57](https://user-images.githubusercontent.com/9803905/38609037-5ed1e676-3d7d-11e8-821e-377e3f46f9c7.png)
---
![bildschirmfoto 2018-04-11 um 11 18 28](https://user-images.githubusercontent.com/9803905/38609058-6b0c84be-3d7d-11e8-9656-405f25805f27.png)

When CSS `display: block` is turned off, it looks fine again (but I guess the html structure is still somewhat off).

So, someone would need to look into creation of the HTML that the descriptions land at the correct place and is targeted by the CSS correctly. I unfortunately do not know how to do that.

> Are you talking about doing changes in here?

Yes, I created a new [branch](https://github.com/basiljs/basiljs.github.io/tree/description-markdown) for it, that you can go ahead and use.

**Comment by fabianmoronzirfas** [comment]
Thanks. I'll take a look ASAP

**Comment by fabianmoronzirfas** [comment]
Yes I will try to make it happen. I can't tell if succeed (I'm not psychic) but I took a look at the source and think this can be done.

**Comment by trych** [comment]
Cool. I am sure it can be done, if I got almost there. I just needed to know if you are on board with the entire "markdown for inline docs" idea. 👍

**Comment by fabianmoronzirfas** [comment]
This should be fixed by ed32dbc or did I miss some description?
