### ISSUE TITLE
Descriptions are cut off at <code> tag

### ISSUE THREAD

**Issue by trych** [basiljs/basiljs.github.io#4]
At the moment descriptions are cut off once the `<code>` tag appears in them. Example see [b.rotate()](https://basiljs.github.io/#rotate). Same for `b.scale()`, `b.translate()` etc.

**Comment by fabianmoronzirfas** [comment]
Hm yeah. Found the error. The docs are still right. If we want to use HTML we need to add the `@description` tag.

**Comment by trych** [comment]
Which branch are the docs generated from? `develop`? The descriptions of these three functions _do_ hold the `@description` tag. So, is it a parsing error?

**Comment by fabianmoronzirfas** [comment]
Yes it is the develop branch. The error I created is as follows (this is also a reminder for me):

The data generator script gets the only element description. This unfortunately gets truncated at HTML tags.

The fix is: 

Get first the std description and later on check if there is a description tag. If so overwrite the std description. 
The description tag has the full description with the HTML.

**Comment by fabianmoronzirfas** [comment]
got it.

**Comment by fabianmoronzirfas** [comment]
https://github.com/basiljs/basil.js/pull/190#issuecomment-301178972
> Great! Thanks a lot. The b.inspect() doc is still the old one though, was it generated from an older version?  

Lets take this discussion into this repo. 
Yes the error came from #5 the api.json should be generated here not in the main repo.  
And pulling in those changes washed another error to the top #6 
unfortunately I can't fix this today. Got a little man crawling around me on the sofa who wants my attention. 👨‍👦
