### ISSUE TITLE
Reference needs to be restructured for better usability

### ISSUE THREAD

**Issue by trych** [basiljs/basiljs.github.io#82]
Hi everyone,
great to see that there is so much work happening on the site, I while I don't comment here often, I still notice some of the issues and such.

Having said that, I think we need to restructure the reference page to make it more usable. I was using [the most up to date version of the reference](https://basiljs2.netlify.com/reference/) in my class this semester and it has become rather difficult to use.

One of the main problems (and one of the differences to the old reference) is that it became really hard to find functions by using the browser's search function. It used to be possible to find a function by searching for `b.functionname`, but since we skipped the `b` now that is not possible anymore. The problem for beginners is, when they are not certain how a function is called and start to search they find a lot of stuff from the description texts first, before they eventually find the actual function (it happened to me all the time this semester, when I was showing the students how to look up stuff in the reference).

My suggestion therefore would be to either

A) restructure it in a way that we only have a list of the function names and then are able to jump to subpages with the descriptions and examples. Examples: [Processing Reference](https://processing.org/reference/), [p5.js Reference](https://p5js.org/reference/).

or

B) restructure it, so we have only the function name and a *short* one-sentence description of the functinality on the main page and then the full description on a sub-page. That way we can give a quick hint to what the function does (and maybe provide additional search terms, but don't spam everything with too many search terms from full descriptions). There is a great example for this here, which I have used in the past few months and I think is very clean (both looking and structured) and very user-friendly: [Kirby CMS Reference](https://getkirby.com/docs/cheatsheet).

@basiljs/basil-js-core-members  Personally I would prefer option B, but I would like to hear other people's opinion as well (and also maybe a feedback by @ffd8, if he had the same issues in his class).

**Comment by fabianmoronzirfas** [comment]
Totally with you on this one. When we started with the reference I took a look into something like lunar.js which is worth a try to have a dynamic search. We already have the sub pages for each entry so we could look into just having the reference with short descriptions and a better search with keywords. How this can be done might take some editorial work on the jsdoc comments.

**Comment by ffd8** [comment]
B -sounds great if you can find a solution for this. Yeah, in class I've ran into issues myself using the CMD+F search on the page, since the constants are always appearing first.. so one has to 'find next..' a few times until hitting the actually useful item (and that only works with experience of what you're looking for). Might be worth trying to wrangle all of the constants together on their own page? or ignore listing them all together and only within the description of each function?

**Comment by fabianmoronzirfas** [comment]
Here is an example for the setup https://lunrjs.com/guides/getting_started.html

**Comment by fabianmoronzirfas** [comment]
So we could introduce the `@summary` jsDoc tag for a short description http://usejsdoc.org/tags-summary.html

**Comment by trych** [comment]
> So we could introduce the @summary jsDoc tag for a short description http://usejsdoc.org/tags-summary.html

Yes, that would be good. We should probably have one commit to the basil.js-repos develop branch that introduces this summary tag in *all* the functions and then have some condition to render the summary only if there is something in it. That way we could add all summaries over time, when we find time for it and don't need to do them all at once.

**Comment by fabianmoronzirfas** [comment]
Would be good to have some to see if it is working

**Comment by fabianmoronzirfas** [comment]
No problem. I'm currently busy with #11 which seems to work pretty well.

**Comment by fabianmoronzirfas** [comment]
I'll get back to the reference index in the next days

**Comment by fabianmoronzirfas** [comment]
Dear @basiljs/basil-js-core-members and @kajetansom,

we have a restructured reference and a working search. You can preview and test it here: 

https://5c2893b942f3db000826a97e--basiljs2.netlify.com

It would be awesome to get some feedback and bug testing on it. The search is on the reference site and also on each entry page.  

It adds some breaking changes:

- removes jquery
- adds webpack

**Comment by trych** [comment]
Awesome work, @fabianmoronzirfas ! Really like this.
I think it needs to be styled a bit better (mainly type sizes and whitespace), but I guess that part could be tackled in the end.

> advanced search notes could fold out/in on click

That would be super cool!

> Currently I also parse the description for the search. Which makes a lot more elements turn up than using only the summary. Should we read the desc or not?

Yes, description should absolutely be searched as well, else we could skip lunr.js, right? Maybe there is a way to give matches in the summary a higher weighting in the search results, so the order reflects the relevance of the search results.

Again, awesome work, thanks a lot!

**Comment by fabianmoronzirfas** [comment]
@trych Yeah styling is still a thing. There is so much room because before I was using the description and truncated it it 150 chars. Which made the boxes a little bit fuller with text. So I'll need to change the min-height of the boxes to match the new summaries.

No we could not skip lunr.js we are searching in codetitle, name, summary and description. I wouldn't want to implement all that fuzzy matching by myself. 🤓 

I took a look. We can boost specific fields. See https://github.com/olivernn/lunr.js/issues/312#issuecomment-399657187 

```js
var idx = lunr(function () {
  this.ref('id')
  this.field('title', { boost: fieldBoost })
  this.field('body')

  documents.forEach(function (doc) {
    this.add(doc, { boost: documentBoost })
  }, this)
})
```

**Comment by fabianmoronzirfas** [comment]
some further fiddeling was done by code monkeys. Please review and have a "guten Rutsch!" https://5c29db4e42b5310008042cb2--basiljs2.netlify.com/reference/

**Comment by ffd8** [comment]
@fabianmoronzirfas this is awesome! just gave a super fast test and the search is fantastic. yeah, much styling to be done on the search, individual pages– but the tree for categories and insta-search is great. Aha.. just realized, it's missing a 'back' button when clicking on an individual function? Would be nice if at the top of that single page reference, it listed a branch style listing for going back.. similar to auction sites: `Reference > Color > colorMode()` – so one could click back to any of those links. Also for some reason 'color' and 'image' sub-functions aren't appearing in the tree. And based on latest link – I preferred previous version, without the vertical dividing lines between functions.. gave all an equal overview for that cat, rather than it looking like the ones in a column have to do with each other (created un-necessary clusters within the cat).

**Comment by fabianmoronzirfas** [comment]
Last build for today https://5c2a297c1d6e9a00096bec8c--basiljs2.netlify.com/reference/

**Comment by b-g** [comment]
Hope you’ve had a nice „Guten Rutsch!“ 🛷 into 2019! 

@fabianmoronzirfas this is mega! Many thanks for this, very helpful and so much better than waht we have now!

I just have minor styling feedback:

* Search text field is not cleared after pressing "Clear" button. Find this is confusing
* A better "zuordnung" of the search results to the search bar would also be helpful. When I first tried it, it took me some split seconds to get that there were already results below. I would either put it more "on top of the page / under the search text filed" e.g. like https://p5js.org/reference/ or give the results a really different visual look e.g. dark background. 
* The hierarchy level "Data#CSV" does not stand out enough. Would be better to reflect more clearly the hierarchy levels from 1 Data > 2  Data#CSV > 3 the basil functions
* The function detail pages are a bit too flat in terms of hierarchy fro me ... but I guess this is not the final final style, or?

🙏
